# Generated by Django 5.1.4 on 2025-03-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='rating_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='user_en_us',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_en_us',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type_ru',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_en_us',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rating_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at_en_us',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at_ru',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
